#!/bin/bash
#
# init script for the raspi-init
#
# Written by Matthew Bogner <matt at ibogner.net>
#
# chkconfig: - 20 85
# description: Initialization script for first boot
#

source /etc/init.d/functions
source /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

start() {
    logger "Running raspi-init..."
    [ -x /boot/raspi-init.sh ] && ( CALLED_BY=init /boot/raspi-init.sh )
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  *)
    echo $"Usage $0 start"
    RETVAL=1
esac

exit $RETVAL
